packages:
  - 'packages/*'
  - 'packages/@ember/*'
  - 'packages/@glimmer/*'
  - 'packages/@glimmer-workspace/*'
  - 'packages/@handlebars/*'
  - 'packages/@types/*'
  - 'packages/*/*/test'
  - 'smoke-tests/*'
  - 'tests/*'

patchedDependencies:
  ember-cli@6.12.0: patches/ember-cli@6.12.0.patch
